@startuml 歌单管理流程

start

:用户进入歌单页面;

if (操作类型？) then (创建歌单)
  :输入歌单信息;
  :保存歌单;
  :创建成功;
else if (编辑歌单)
  :修改歌单信息;
  :更新数据库;
  :保存成功;
else if (删除歌单)
  :确认删除;
  if (确认？) then (是)
    :删除歌单及关联;
    :删除成功;
  else (否)
    :取消操作;
  endif
else if (管理歌曲)
  :选择添加/移除歌曲;
  :更新关联表;
  :操作成功;
endif

:刷新歌单列表;
stop

@enduml